# Merge social and crypto pricing data with original dataset

In [1]:
import os
import pandas as pd
import numpy as np
os.getcwd()

'/home/jupyter/nft/nft_capstone'

In [2]:
df = pd.read_csv('https://storage.googleapis.com/nft_capstone_datafiles/Data_API.csv.gz',
                dtype={'Smart_contract':str, 'ID_token':str, 'Transaction_hash':str,'Seller_username':str,'Buyer_username':str,'Image_url_2':str,
                        'Image_url_3':str,'Image_url_4':str,'Name':str,'Description':str,'Permanent_link':str})
print(len(df))
print(df.columns)
df.head(5)

6071027
Index(['Smart_contract', 'ID_token', 'Transaction_hash', 'Seller_address',
       'Seller_username', 'Buyer_address', 'Buyer_username', 'Image_url_1',
       'Image_url_2', 'Image_url_3', 'Image_url_4', 'Price_Crypto', 'Crypto',
       'Price_USD', 'Name', 'Description', 'Collection', 'Market',
       'Datetime_updated', 'Datetime_updated_seconds', 'Permanent_link',
       'Unique_id_collection', 'Collection_cleaned', 'Category'],
      dtype='object')

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Name,Description,Collection,Market,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category
0,NaN,87094722.0,0xed9ff1c311a611e5c457ce0a49bbbb7ed55efca98842...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '87094722.0')",Godsunchained,Games
1,NaN,73044643.0,0xbc8412594ffa7382e8306215ece5b4e041fc641b1813...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=79&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '73044643.0')",Godsunchained,Games
2,NaN,17107482.0,0x92672baf5e9e23de230dee8e57ddf443ab6d5a336341...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '17107482.0')",Godsunchained,Games
3,NaN,82230857.0,0x3d157249e3083622c2d756f07a05caa3a76687288b32...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=227&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '82230857.0')",Godsunchained,Games
4,NaN,40925443.0,0xa892b3569dc8e6b3c7db93aade62372637ebbc61fb63...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=62&q=4,NaN,NaN,...,NaN,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:58:44,NaN,"('Godsunchained', '40925443.0')",Godsunchained,Games

In [5]:
df['Datetime_updated_dt'] = pd.to_datetime(df['Datetime_updated'])
df.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Description,Collection,Market,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category,Datetime_updated_dt
0,NaN,87094722.0,0xed9ff1c311a611e5c457ce0a49bbbb7ed55efca98842...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '87094722.0')",Godsunchained,Games,2019-11-30
1,NaN,73044643.0,0xbc8412594ffa7382e8306215ece5b4e041fc641b1813...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=79&q=4,NaN,NaN,...,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '73044643.0')",Godsunchained,Games,2019-11-30
2,NaN,17107482.0,0x92672baf5e9e23de230dee8e57ddf443ab6d5a336341...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '17107482.0')",Godsunchained,Games,2019-11-30
3,NaN,82230857.0,0x3d157249e3083622c2d756f07a05caa3a76687288b32...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=227&q=4,NaN,NaN,...,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '82230857.0')",Godsunchained,Games,2019-11-30
4,NaN,40925443.0,0xa892b3569dc8e6b3c7db93aade62372637ebbc61fb63...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=62&q=4,NaN,NaN,...,NaN,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:58:44,NaN,"('Godsunchained', '40925443.0')",Godsunchained,Games,2019-11-30

In [6]:
df['Datetime_daybeforesale'] = df['Datetime_updated_dt'] - pd.Timedelta(days=1)
df.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Collection,Market,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category,Datetime_updated_dt,Datetime_daybeforesale
0,NaN,87094722.0,0xed9ff1c311a611e5c457ce0a49bbbb7ed55efca98842...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '87094722.0')",Godsunchained,Games,2019-11-30,2019-11-29
1,NaN,73044643.0,0xbc8412594ffa7382e8306215ece5b4e041fc641b1813...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=79&q=4,NaN,NaN,...,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '73044643.0')",Godsunchained,Games,2019-11-30,2019-11-29
2,NaN,17107482.0,0x92672baf5e9e23de230dee8e57ddf443ab6d5a336341...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '17107482.0')",Godsunchained,Games,2019-11-30,2019-11-29
3,NaN,82230857.0,0x3d157249e3083622c2d756f07a05caa3a76687288b32...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=227&q=4,NaN,NaN,...,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '82230857.0')",Godsunchained,Games,2019-11-30,2019-11-29
4,NaN,40925443.0,0xa892b3569dc8e6b3c7db93aade62372637ebbc61fb63...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=62&q=4,NaN,NaN,...,Godsunchained,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:58:44,NaN,"('Godsunchained', '40925443.0')",Godsunchained,Games,2019-11-30,2019-11-29

In [7]:
df['nft_sales_count'] = df.groupby(['Unique_id_collection'])['Unique_id_collection'].transform('count')
# print(df.columns)
df.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Market,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category,Datetime_updated_dt,Datetime_daybeforesale,nft_sales_count
0,NaN,87094722.0,0xed9ff1c311a611e5c457ce0a49bbbb7ed55efca98842...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '87094722.0')",Godsunchained,Games,2019-11-30,2019-11-29,1
1,NaN,73044643.0,0xbc8412594ffa7382e8306215ece5b4e041fc641b1813...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=79&q=4,NaN,NaN,...,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '73044643.0')",Godsunchained,Games,2019-11-30,2019-11-29,1
2,NaN,17107482.0,0x92672baf5e9e23de230dee8e57ddf443ab6d5a336341...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0xe0fb7622091e3d9ef9b438471b10b9ea88c7cf6b,NaN,https://card.godsunchained.com/?id=33&q=4,NaN,NaN,...,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '17107482.0')",Godsunchained,Games,2019-11-30,2019-11-29,1
3,NaN,82230857.0,0x3d157249e3083622c2d756f07a05caa3a76687288b32...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=227&q=4,NaN,NaN,...,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:59:33,NaN,"('Godsunchained', '82230857.0')",Godsunchained,Games,2019-11-30,2019-11-29,1
4,NaN,40925443.0,0xa892b3569dc8e6b3c7db93aade62372637ebbc61fb63...,0x76481caa104b5f6bccb540dae4cefaf1c398ebea,NaN,0x2c00d05ff7ffe93d77145dfe12aa56e622ae6f40,NaN,https://card.godsunchained.com/?id=62&q=4,NaN,NaN,...,Godsunchained,2019-11-30 00:00:00,2019-11-30 23:58:44,NaN,"('Godsunchained', '40925443.0')",Godsunchained,Games,2019-11-30,2019-11-29,1

In [8]:
df_sorted = df.sort_values(['Category', 'Collection_cleaned', 'Datetime_updated_seconds'])
df_sorted['First_item_Collection_cleaned'] = 0
df_sorted.loc[df_sorted['Collection_cleaned'] != df_sorted['Collection_cleaned'].shift(1), 'First_item_Collection_cleaned'] = 1

In [9]:
df_sorted.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Datetime_updated,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category,Datetime_updated_dt,Datetime_daybeforesale,nft_sales_count,First_item_Collection_cleaned
4561207,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,59,0xf31852b040f32d14322e1b599cac38eadedb1e145cfc...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0xfdc34f61ccc6e5cbf8d168614ab29bae624085c9,KM-ATT,https://lh3.googleusercontent.com/SLoh29AeY88B...,http://www.aicryptoart.org/artpieces/59__Great...,https://lh3.googleusercontent.com/SLoh29AeY88B...,...,2019-09-09 00:00:00,2019-09-09 20:00:35,https://opensea.io/assets/0x8ae8d2ae74a96595bc...,"('Aicryptoart', '59')",Ai,Art,2019-09-09,2019-09-08,1,1
4559557,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,39,0x59c45346fed5b753e0ce1d51dd9d56e1df5a27dd620d...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x73aab1333dc134e34f5c7b492f90e76cd7589476,rabanheidr,https://lh3.googleusercontent.com/JqKxBV1odtH7...,http://www.aicryptoart.org/artpieces/39__Mr._P...,https://lh3.googleusercontent.com/JqKxBV1odtH7...,...,2019-09-13 00:00:00,2019-09-13 22:35:55,https://opensea.io/assets/0x8ae8d2ae74a96595bc...,"('Aicryptoart', '39')",Ai,Art,2019-09-13,2019-09-12,1,0
4696188,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,23,0xcd79d4cd1d12c00fcc06a2f3f9eef408fe03dccadecd...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x187d6e8741af35c45198ebec83905eb23e742b15,ciobo,https://lh3.googleusercontent.com/31JMA6rmMom6...,http://www.aicryptoart.org/artpieces/23_dont_f...,https://lh3.googleusercontent.com/31JMA6rmMom6...,...,2019-11-03 00:00:00,2019-11-03 08:20:12,https://opensea.io/assets/0x8ae8d2ae74a96595bc...,"('Aicryptoart', '23')",Ai,Art,2019-11-03,2019-11-02,1,0
4683044,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,28,0x9efbadc255a3b7b68b78b1f497787a3d2366c3799359...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x1eef91b7db2848a528a0762b0c5327a53b2eadbe,Lifenow,https://lh3.googleusercontent.com/ZRDrLtIrl0qv...,http://www.aicryptoart.org/artpieces/28__Mrs._...,https://lh3.googleusercontent.com/ZRDrLtIrl0qv...,...,2019-11-17 00:00:00,2019-11-17 18:55:04,https://opensea.io/assets/0x8ae8d2ae74a96595bc...,"('Aicryptoart', '28')",Ai,Art,2019-11-17,2019-11-16,1,0
4722287,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,26,0x82fc5f80b55584526ebbfad26329f9e24e4626338376...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0xcd4fec10c8ad4873e209062b31defb684ff8cb7c,cryptotonya,https://lh3.googleusercontent.com/MfxXntL-jf1-...,http://www.aicryptoart.org/artpieces/26__Prof....,https://lh3.googleusercontent.com/MfxXntL-jf1-...,...,2019-12-23 00:00:00,2019-12-23 03:15:21,https://opensea.io/assets/0x8ae8d2ae74a96595bc...,"('Aicryptoart', '26')",Ai,Art,2019-12-23,2019-12-22,1,0

In [10]:
df_sorted = df_sorted.sort_values(['Category', 'Collection_cleaned', 'Unique_id_collection', 'Datetime_updated_seconds'])
df_sorted['First_item_Unique_id_collection'] = 0
df_sorted.loc[df_sorted['Unique_id_collection'] != df_sorted['Unique_id_collection'].shift(1), 'First_item_Unique_id_collection'] = 1
df_sorted.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Datetime_updated_seconds,Permanent_link,Unique_id_collection,Collection_cleaned,Category,Datetime_updated_dt,Datetime_daybeforesale,nft_sales_count,First_item_Collection_cleaned,First_item_Unique_id_collection
2424685,atomicassets,1099529651021,NaN,et4b2.wam,NaN,tnsr2.wam,NaN,NaN,NaN,NaN,...,2021-04-27 11:57:34,NaN,"('12airdrop345', '1099529651021')",Ai,Art,2021-04-27,2021-04-26,1,0,1
5162438,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,1,0x4374cfdea67e7fb70d7c4ffeea1b27b22fc8196c7f98...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x240ad467a71210629d71d4de22ebde27951c83fc,Collin3,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,https://ipfs.daonomic.com/ipfs/QmUxrkYzFdkHS6J...,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,...,2020-06-20 12:10:38,https://opensea.io/assets/0x5f4becdcfcbeaf8274...,"('Ai-abstract', '1')",Ai,Art,2020-06-20,2020-06-19,1,0,1
5155787,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,14,0x92ad9a1bae02b7e9fbbd6c91b4cbe4c381d8a60939b2...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/QBOo6swyDyKq...,https://cloudflare-ipfs.com/ipfs/QmSZzC7Ja3yeB...,https://lh3.googleusercontent.com/QBOo6swyDyKq...,...,2020-06-29 03:47:35,https://opensea.io/assets/0x5f4becdcfcbeaf8274...,"('Ai-abstract', '14')",Ai,Art,2020-06-29,2020-06-28,1,0,1
5188628,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,15,0xc23f339be74bf3ce17bd0dc51c9e4ecbc33a5d58017a...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,https://cloudflare-ipfs.com/ipfs/QmTXVmmBnPyR7...,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,...,2020-07-20 19:53:37,https://opensea.io/assets/0x5f4becdcfcbeaf8274...,"('Ai-abstract', '15')",Ai,Art,2020-07-20,2020-07-19,1,0,1
5157199,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,16,0xe9222ae3f60758ae5e3f3bedcfe77b9054ed7fa0f575...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x8124b02b4967bd7338a450420a572d574915ff9c,Collin2,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,https://ipfs.io/ipfs/Qmb3aZZiwPnNARK2UpqYRzkAr...,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,...,2020-06-27 06:49:28,https://opensea.io/assets/0x5f4becdcfcbeaf8274...,"('Ai-abstract', '16')",Ai,Art,2020-06-27,2020-06-26,1,0,1

In [11]:
df_sorted['Previous_Price_USD'] = df_sorted['Price_USD'].shift(1)
df_sorted['Previous_Datetime_updated_seconds'] = df_sorted['Datetime_updated_seconds'].shift(1)
df_sorted['Elapsed_time'] = np.where(df_sorted['First_item_Unique_id_collection'] == 1, pd.NaT, 
                                     pd.to_datetime(df_sorted['Datetime_updated_seconds']) - pd.to_datetime(df_sorted['Previous_Datetime_updated_seconds']))
df_sorted['Price_increase'] = np.where(df_sorted['First_item_Unique_id_collection'] == 1, 0, 
                                       np.where(df_sorted['Price_USD']-df_sorted['Previous_Price_USD']>0,1,0))
df_sorted['Price_diff'] = np.where(df_sorted['First_item_Unique_id_collection'] == 1, np.NaN, df_sorted['Price_USD']-df_sorted['Previous_Price_USD'])
df_sorted['Price_diff_pctg'] = np.where(df_sorted['First_item_Unique_id_collection'] == 1, np.NaN, 
                                        (df_sorted['Price_USD']/df_sorted['Previous_Price_USD'])-1)
df_sorted.head(5)

# df_classification2['Price_increase'] = np.where(df_classification2['First_item_Unique_id_collection'] == 1, 0, df_classification2['Price_increase'])
# df_classification2['Price_diff'] = np.where(df_classification2['First_item_Unique_id_collection'] == 1, np.NaN, df_classification2['Price_diff'])
# df_classification2['Price_diff_pctg'] = np.where(df_classification2['First_item_Unique_id_collection'] == 1, np.NaN, df_classification2['Price_diff_pctg'])
# df_classification2['Elapsed_time'] = np.where(df_classification2['First_item_Unique_id_collection'] == 1, pd.NaT, df_classification2['Elapsed_time'])

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,Datetime_daybeforesale,nft_sales_count,First_item_Collection_cleaned,First_item_Unique_id_collection,Previous_Price_USD,Previous_Datetime_updated_seconds,Elapsed_time,Price_increase,Price_diff,Price_diff_pctg
2424685,atomicassets,1099529651021,NaN,et4b2.wam,NaN,tnsr2.wam,NaN,NaN,NaN,NaN,...,2021-04-26,1,0,1,NaN,NaN,NaT,0,NaN,NaN
5162438,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,1,0x4374cfdea67e7fb70d7c4ffeea1b27b22fc8196c7f98...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x240ad467a71210629d71d4de22ebde27951c83fc,Collin3,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,https://ipfs.daonomic.com/ipfs/QmUxrkYzFdkHS6J...,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,...,2020-06-19,1,0,1,0.18970,2021-04-27 11:57:34,NaT,0,NaN,NaN
5155787,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,14,0x92ad9a1bae02b7e9fbbd6c91b4cbe4c381d8a60939b2...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/QBOo6swyDyKq...,https://cloudflare-ipfs.com/ipfs/QmSZzC7Ja3yeB...,https://lh3.googleusercontent.com/QBOo6swyDyKq...,...,2020-06-28,1,0,1,34.47900,2020-06-20 12:10:38,NaT,0,NaN,NaN
5188628,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,15,0xc23f339be74bf3ce17bd0dc51c9e4ecbc33a5d58017a...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,https://cloudflare-ipfs.com/ipfs/QmTXVmmBnPyR7...,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,...,2020-07-19,1,0,1,33.98325,2020-06-29 03:47:35,NaT,0,NaN,NaN
5157199,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,16,0xe9222ae3f60758ae5e3f3bedcfe77b9054ed7fa0f575...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x8124b02b4967bd7338a450420a572d574915ff9c,Collin2,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,https://ipfs.io/ipfs/Qmb3aZZiwPnNARK2UpqYRzkAr...,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,...,2020-06-26,1,0,1,35.52825,2020-07-20 19:53:37,NaT,0,NaN,NaN

In [12]:
df_sorted.groupby('Collection_cleaned')['Unique_id_collection'].count()
# df_sorted.loc[df_sorted['Collection_cleaned'] == 'Abacu']

Collection_cleaned
Aaronsartistry                  57
Aasgard                         10
Aavegotchi                    2388
Abacu                          142
Abeautifulthingawaitsusall       2
                              ...
Zuphy                            3
Zuzumazu                         2
Zweihspacert                     1
Zyzzyvasalgorithmicart          10
Zzsun                            2
Name: Unique_id_collection, Length: 4624, dtype: int64

In [15]:
df_sorted.groupby(['Collection_cleaned','Datetime_daybeforesale'])['Price_USD'].expanding().median().values

array([ 38.7324,  53.2884,  53.2884, ...,  90.9175, 447.93  ,  72.734 ])

In [16]:
# df_test = df_sorted.loc[df_sorted['Collection_cleaned'] == 'Abacu']
# df_test.to_csv('df_Abacu_collection.csv')

## Add otherdata

In [17]:
df_otherdata = pd.read_csv('https://storage.googleapis.com/nft_capstone_datafiles/df_otherdata.csv')
print(len(df_otherdata))
df_otherdata.head(5)

1676

,Unnamed: 0,Date,GoogleTrends,BTC_price,ETH_price,MANA_price,WAX_price,GoogleTrends_7d_rolling_avg,GoogleTrends_14d_rolling_avg,GoogleTrends_30d_rolling_avg,...,MANA_price_7d_rolling_avg,MANA_price_14d_rolling_avg,MANA_price_30d_rolling_avg,MANA_price_60d_rolling_avg,MANA_price_90d_rolling_avg,WAX_price_7d_rolling_avg,WAX_price_14d_rolling_avg,WAX_price_30d_rolling_avg,WAX_price_60d_rolling_avg,WAX_price_90d_rolling_avg
0,0,2017-07-01,0,2424.6,255.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2017-07-02,0,2536.5,277.64,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2017-07-03,0,2572.5,273.99,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2017-07-04,0,2617.3,266.68,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2017-07-05,0,2627.9,264.77,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
print(type(df_sorted['Datetime_daybeforesale']))
print(type(df_sorted['Datetime_daybeforesale'][0]))
print(type(df_otherdata['Date']))
print(type(df_otherdata['Date'][0]))

<class 'pandas.core.series.Series'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas.core.series.Series'>
<class 'str'>

In [19]:
df_otherdata['Date_new'] = pd.to_datetime(df_otherdata['Date'])

In [20]:
print(type(df_otherdata['Date_new'][0]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [21]:
df_sorted2 = pd.merge(df_sorted, df_otherdata, how='left', left_on='Datetime_daybeforesale', right_on='Date_new')
print(len(df_sorted2))
print(df_sorted2.columns)
df_sorted2.head(5)

6071027
Index(['Smart_contract', 'ID_token', 'Transaction_hash', 'Seller_address',
       'Seller_username', 'Buyer_address', 'Buyer_username', 'Image_url_1',
       'Image_url_2', 'Image_url_3', 'Image_url_4', 'Price_Crypto', 'Crypto',
       'Price_USD', 'Name', 'Description', 'Collection', 'Market',
       'Datetime_updated', 'Datetime_updated_seconds', 'Permanent_link',
       'Unique_id_collection', 'Collection_cleaned', 'Category',
       'Datetime_updated_dt', 'Datetime_daybeforesale', 'nft_sales_count',
       'First_item_Collection_cleaned', 'First_item_Unique_id_collection',
       'Previous_Price_USD', 'Previous_Datetime_updated_seconds',
       'Elapsed_time', 'Price_increase', 'Price_diff', 'Price_diff_pctg',
       'Unnamed: 0', 'Date', 'GoogleTrends', 'BTC_price', 'ETH_price',
       'MANA_price', 'WAX_price', 'GoogleTrends_7d_rolling_avg',
       'GoogleTrends_14d_rolling_avg', 'GoogleTrends_30d_rolling_avg',
       'GoogleTrends_60d_rolling_avg', 'GoogleTrends_90d_rolling_avg',
       'BTC_price_7d_rolling_avg', 'BTC_price_14d_rolling_avg',
       'BTC_price_30d_rolling_avg', 'BTC_price_60d_rolling_avg',
       'BTC_price_90d_rolling_avg', 'ETH_price_7d_rolling_avg',
       'ETH_price_14d_rolling_avg', 'ETH_price_30d_rolling_avg',
       'ETH_price_60d_rolling_avg', 'ETH_price_90d_rolling_avg',
       'MANA_price_7d_rolling_avg', 'MANA_price_14d_rolling_avg',
       'MANA_price_30d_rolling_avg', 'MANA_price_60d_rolling_avg',
       'MANA_price_90d_rolling_avg', 'WAX_price_7d_rolling_avg',
       'WAX_price_14d_rolling_avg', 'WAX_price_30d_rolling_avg',
       'WAX_price_60d_rolling_avg', 'WAX_price_90d_rolling_avg', 'Date_new'],
      dtype='object')

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,MANA_price_14d_rolling_avg,MANA_price_30d_rolling_avg,MANA_price_60d_rolling_avg,MANA_price_90d_rolling_avg,WAX_price_7d_rolling_avg,WAX_price_14d_rolling_avg,WAX_price_30d_rolling_avg,WAX_price_60d_rolling_avg,WAX_price_90d_rolling_avg,Date_new
0,atomicassets,1099529651021,NaN,et4b2.wam,NaN,tnsr2.wam,NaN,NaN,NaN,NaN,...,1.256379,1.135387,0.900117,0.680749,0.182829,0.208000,0.237567,0.211652,0.161368,2021-04-26
1,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,1,0x4374cfdea67e7fb70d7c4ffeea1b27b22fc8196c7f98...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x240ad467a71210629d71d4de22ebde27951c83fc,Collin3,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,https://ipfs.daonomic.com/ipfs/QmUxrkYzFdkHS6J...,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,...,0.041500,0.040693,0.037338,0.033691,0.057057,0.062343,0.055010,0.043875,0.039044,2020-06-19
2,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,14,0x92ad9a1bae02b7e9fbbd6c91b4cbe4c381d8a60939b2...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/QBOo6swyDyKq...,https://cloudflare-ipfs.com/ipfs/QmSZzC7Ja3yeB...,https://lh3.googleusercontent.com/QBOo6swyDyKq...,...,0.041579,0.041500,0.039113,0.035419,0.051529,0.053300,0.057263,0.046888,0.041167,2020-06-28
3,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,15,0xc23f339be74bf3ce17bd0dc51c9e4ecbc33a5d58017a...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,https://cloudflare-ipfs.com/ipfs/QmTXVmmBnPyR7...,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,...,0.040143,0.040270,0.040482,0.038316,0.054129,0.054643,0.054013,0.054512,0.047254,2020-07-19
4,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,16,0xe9222ae3f60758ae5e3f3bedcfe77b9054ed7fa0f575...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x8124b02b4967bd7338a450420a572d574915ff9c,Collin2,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,https://ipfs.io/ipfs/Qmb3aZZiwPnNARK2UpqYRzkAr...,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,...,0.042257,0.041667,0.038973,0.035111,0.053043,0.055050,0.057150,0.046438,0.040793,2020-06-26

In [22]:
df_sorted3 = df_sorted2.drop(columns=['Unnamed: 0', 'Date', 'Date_new'])

In [23]:
print(df_sorted3['Datetime_updated'].min())
df_sorted3['Datetime_updated'].max()

2017-11-23 00:00:00

'2021-04-27 00:00:00'

## Add GoogleTrends by Collection data

In [24]:
df_googletrends_collection_daily = pd.read_csv('https://storage.googleapis.com/nft_capstone_datafiles/df_googletrends_collection_daily_rolling.csv')
print(len(df_googletrends_collection_daily))
df_googletrends_collection_daily.head(5)

279200

,Unnamed: 0,date,Collection,Ggl_trends_collection,Ggl_trends_collection_7d_rolling_avg,Ggl_trends_collection_14d_rolling_avg,Ggl_trends_collection_30d_rolling_avg,Ggl_trends_collection_60d_rolling_avg,Ggl_trends_collection_90d_rolling_avg
0,0,2017-07-02,13,0.0,0.0,0.0,0.0,0.0,0.0
1,200,2017-07-03,13,0.0,0.0,0.0,0.0,0.0,0.0
2,400,2017-07-04,13,0.0,0.0,0.0,0.0,0.0,0.0
3,600,2017-07-05,13,0.0,0.0,0.0,0.0,0.0,0.0
4,800,2017-07-06,13,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df_googletrends_collection_daily2 = df_googletrends_collection_daily.drop(columns=['Unnamed: 0'])
df_googletrends_collection_daily2.head()

,date,Collection,Ggl_trends_collection,Ggl_trends_collection_7d_rolling_avg,Ggl_trends_collection_14d_rolling_avg,Ggl_trends_collection_30d_rolling_avg,Ggl_trends_collection_60d_rolling_avg,Ggl_trends_collection_90d_rolling_avg
0,2017-07-02,13,0.0,0.0,0.0,0.0,0.0,0.0
1,2017-07-03,13,0.0,0.0,0.0,0.0,0.0,0.0
2,2017-07-04,13,0.0,0.0,0.0,0.0,0.0,0.0
3,2017-07-05,13,0.0,0.0,0.0,0.0,0.0,0.0
4,2017-07-06,13,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
df_googletrends_collection_daily2['date_new'] = pd.to_datetime(df_googletrends_collection_daily2['date'])

In [27]:
df_sorted4 = pd.merge(df_sorted3, df_googletrends_collection_daily2, how='left', left_on=['Collection', 'Datetime_daybeforesale'], right_on=['Collection', 'date_new'])
print(len(df_sorted4))
print(df_sorted4.columns)
df_sorted4.head()

6071027
Index(['Smart_contract', 'ID_token', 'Transaction_hash', 'Seller_address',
       'Seller_username', 'Buyer_address', 'Buyer_username', 'Image_url_1',
       'Image_url_2', 'Image_url_3', 'Image_url_4', 'Price_Crypto', 'Crypto',
       'Price_USD', 'Name', 'Description', 'Collection', 'Market',
       'Datetime_updated', 'Datetime_updated_seconds', 'Permanent_link',
       'Unique_id_collection', 'Collection_cleaned', 'Category',
       'Datetime_updated_dt', 'Datetime_daybeforesale', 'nft_sales_count',
       'First_item_Collection_cleaned', 'First_item_Unique_id_collection',
       'Previous_Price_USD', 'Previous_Datetime_updated_seconds',
       'Elapsed_time', 'Price_increase', 'Price_diff', 'Price_diff_pctg',
       'GoogleTrends', 'BTC_price', 'ETH_price', 'MANA_price', 'WAX_price',
       'GoogleTrends_7d_rolling_avg', 'GoogleTrends_14d_rolling_avg',
       'GoogleTrends_30d_rolling_avg', 'GoogleTrends_60d_rolling_avg',
       'GoogleTrends_90d_rolling_avg', 'BTC_price_7d_rolling_avg',
       'BTC_price_14d_rolling_avg', 'BTC_price_30d_rolling_avg',
       'BTC_price_60d_rolling_avg', 'BTC_price_90d_rolling_avg',
       'ETH_price_7d_rolling_avg', 'ETH_price_14d_rolling_avg',
       'ETH_price_30d_rolling_avg', 'ETH_price_60d_rolling_avg',
       'ETH_price_90d_rolling_avg', 'MANA_price_7d_rolling_avg',
       'MANA_price_14d_rolling_avg', 'MANA_price_30d_rolling_avg',
       'MANA_price_60d_rolling_avg', 'MANA_price_90d_rolling_avg',
       'WAX_price_7d_rolling_avg', 'WAX_price_14d_rolling_avg',
       'WAX_price_30d_rolling_avg', 'WAX_price_60d_rolling_avg',
       'WAX_price_90d_rolling_avg', 'date', 'Ggl_trends_collection',
       'Ggl_trends_collection_7d_rolling_avg',
       'Ggl_trends_collection_14d_rolling_avg',
       'Ggl_trends_collection_30d_rolling_avg',
       'Ggl_trends_collection_60d_rolling_avg',
       'Ggl_trends_collection_90d_rolling_avg', 'date_new'],
      dtype='object')

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,WAX_price_60d_rolling_avg,WAX_price_90d_rolling_avg,date,Ggl_trends_collection,Ggl_trends_collection_7d_rolling_avg,Ggl_trends_collection_14d_rolling_avg,Ggl_trends_collection_30d_rolling_avg,Ggl_trends_collection_60d_rolling_avg,Ggl_trends_collection_90d_rolling_avg,date_new
0,atomicassets,1099529651021,NaN,et4b2.wam,NaN,tnsr2.wam,NaN,NaN,NaN,NaN,...,0.211652,0.161368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,1,0x4374cfdea67e7fb70d7c4ffeea1b27b22fc8196c7f98...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x240ad467a71210629d71d4de22ebde27951c83fc,Collin3,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,https://ipfs.daonomic.com/ipfs/QmUxrkYzFdkHS6J...,https://lh3.googleusercontent.com/m3HxAVcw1nhK...,...,0.043875,0.039044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,14,0x92ad9a1bae02b7e9fbbd6c91b4cbe4c381d8a60939b2...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/QBOo6swyDyKq...,https://cloudflare-ipfs.com/ipfs/QmSZzC7Ja3yeB...,https://lh3.googleusercontent.com/QBOo6swyDyKq...,...,0.046888,0.041167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,15,0xc23f339be74bf3ce17bd0dc51c9e4ecbc33a5d58017a...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0xf52393e120f918ffba50410b90a29b1f8250c879,ModeratsArt,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,https://cloudflare-ipfs.com/ipfs/QmTXVmmBnPyR7...,https://lh3.googleusercontent.com/zOJ70FhsTsAt...,...,0.054512,0.047254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,16,0xe9222ae3f60758ae5e3f3bedcfe77b9054ed7fa0f575...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x8124b02b4967bd7338a450420a572d574915ff9c,Collin2,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,https://ipfs.io/ipfs/Qmb3aZZiwPnNARK2UpqYRzkAr...,https://lh3.googleusercontent.com/mjhoFcM3C9hu...,...,0.046438,0.040793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

## Add rolling median

In [28]:
df_sorted4.index

Int64Index([      0,       1,       2,       3,       4,       5,       6,
                  7,       8,       9,
            ...
            6071017, 6071018, 6071019, 6071020, 6071021, 6071022, 6071023,
            6071024, 6071025, 6071026],
           dtype='int64', length=6071027)

In [29]:
df_sorted5 = df_sorted4.drop(columns=['date', 'date_new'])

In [30]:
df_sorted5 = df_sorted5.sort_values(['Category', 'Collection_cleaned', 'Datetime_updated_seconds'])
df_sorted5.head(10)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,WAX_price_14d_rolling_avg,WAX_price_30d_rolling_avg,WAX_price_60d_rolling_avg,WAX_price_90d_rolling_avg,Ggl_trends_collection,Ggl_trends_collection_7d_rolling_avg,Ggl_trends_collection_14d_rolling_avg,Ggl_trends_collection_30d_rolling_avg,Ggl_trends_collection_60d_rolling_avg,Ggl_trends_collection_90d_rolling_avg
644,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,59,0xf31852b040f32d14322e1b599cac38eadedb1e145cfc...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0xfdc34f61ccc6e5cbf8d168614ab29bae624085c9,KM-ATT,https://lh3.googleusercontent.com/SLoh29AeY88B...,http://www.aicryptoart.org/artpieces/59__Great...,https://lh3.googleusercontent.com/SLoh29AeY88B...,...,0.042964,0.049710,0.053525,0.065018,NaN,NaN,NaN,NaN,NaN,NaN
641,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,39,0x59c45346fed5b753e0ce1d51dd9d56e1df5a27dd620d...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x73aab1333dc134e34f5c7b492f90e76cd7589476,rabanheidr,https://lh3.googleusercontent.com/JqKxBV1odtH7...,http://www.aicryptoart.org/artpieces/39__Mr._P...,https://lh3.googleusercontent.com/JqKxBV1odtH7...,...,0.041036,0.046837,0.052652,0.062263,NaN,NaN,NaN,NaN,NaN,NaN
635,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,23,0xcd79d4cd1d12c00fcc06a2f3f9eef408fe03dccadecd...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x187d6e8741af35c45198ebec83905eb23e742b15,ciobo,https://lh3.googleusercontent.com/31JMA6rmMom6...,http://www.aicryptoart.org/artpieces/23_dont_f...,https://lh3.googleusercontent.com/31JMA6rmMom6...,...,0.030307,0.029983,0.034100,0.040282,NaN,NaN,NaN,NaN,NaN,NaN
639,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,28,0x9efbadc255a3b7b68b78b1f497787a3d2366c3799359...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x1eef91b7db2848a528a0762b0c5327a53b2eadbe,Lifenow,https://lh3.googleusercontent.com/ZRDrLtIrl0qv...,http://www.aicryptoart.org/artpieces/28__Mrs._...,https://lh3.googleusercontent.com/ZRDrLtIrl0qv...,...,0.030857,0.030293,0.031777,0.036091,NaN,NaN,NaN,NaN,NaN,NaN
638,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,26,0x82fc5f80b55584526ebbfad26329f9e24e4626338376...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0xcd4fec10c8ad4873e209062b31defb684ff8cb7c,cryptotonya,https://lh3.googleusercontent.com/MfxXntL-jf1-...,http://www.aicryptoart.org/artpieces/26__Prof....,https://lh3.googleusercontent.com/MfxXntL-jf1-...,...,0.022436,0.023727,0.026798,0.028288,NaN,NaN,NaN,NaN,NaN,NaN
634,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,21,0x74e0c527247d70c334ae9de83d6b28d296703588d24b...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x16c13e902250a70bad5382cb38934a7ae1ac82f5,Elephantul,https://lh3.googleusercontent.com/QJa11TP5ZALQ...,http://www.aicryptoart.org/artpieces/21_Water_...,https://lh3.googleusercontent.com/QJa11TP5ZALQ...,...,0.022436,0.023727,0.026798,0.028288,NaN,NaN,NaN,NaN,NaN,NaN
630,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,18,0xc9cbdfeaae0b56646844eba98d2d83da098707b82a19...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x61592a6f682bbabfd743aa7596ee269e7448212c,AceKennedy,https://lh3.googleusercontent.com/sqP3FLVmlLr6...,http://www.aicryptoart.org/artpieces/18_Specia...,https://lh3.googleusercontent.com/sqP3FLVmlLr6...,...,0.047007,0.037460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,0x5f4becdcfcbeaf8274b6905b101aaf44ac10012c,4,0x27884bfc23ecc43021cce80042e5cbb6b57b21a5aa86...,0xdc546f477f273bcf327297bf4adcb671b5f20be1,BlackBoxDotArt,0x6853a596d6d7264d3622546da3b891b6fe17eb82,zaphodok,https://lh3.googleusercontent.com/K2gE9CapNDIM...,https://ipfs.daonomic.com/ipfs/QmZuqY81Lq3AwXQ...,https://lh3.googleusercontent.com/K2gE9CapNDIM...,...,0.033536,0.031493,0.031293,0.035808,NaN,NaN,NaN,NaN,NaN,NaN
593,0xef547d017f64863a1a741864d900956081744238,7,0x07dc848c0bdaa4958ff8c6e5ac998d9729a82daa5918...,0x4f3d8fe6eecbf30b9987da8def9e45a67e45147b,Science,0x1ea948c321e4d96a7b358ef0fe3cfc51d7db6424,Levy,https://lh3.googleusercontent.com/XnB7qFcN_Q3S...,NaN,https://lh3.googleusercontent.com/XnB7qFcN_Q3S...,...,0.040657,0.036513,0.033118,0.034360,NaN,NaN,NaN,NaN,NaN,NaN
590,0xef547d017f64863a1a741864d900956081744238,61,0xecfb3510d3301bdc2d0b1e062085b8ece49500122e97...,0x73b4437a4b3e43de673836107437e4f092a363e0,Bitcoin,0x1ea948c321e4d96a7b358ef0fe3cfc51d7db6424,Levy,https://lh3.googleusercontent.com/ZQLB6bkWmM7H...,NaN,https://lh3.googleusercontent.com/ZQLB6bkWmM7H...,...,0.040657,0.036513,0.033118,0.034360,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Create smaller dataframe with
# Collection_cleaned
# Datetime_updated
# Price_USD
# Price_Crypto

df_sorted5_priceprep = df_sorted5[['Collection_cleaned', 'Datetime_updated', 'Price_USD', 'Price_Crypto']]
print(len(df_sorted5_priceprep))
df_sorted5_priceprep.head(5)

6071027

    Collection_cleaned     Datetime_updated  Price_USD  Price_Crypto
644                 Ai  2019-09-09 00:00:00   0.001805       0.00001
641                 Ai  2019-09-13 00:00:00   1.631295       0.00900
635                 Ai  2019-11-03 00:00:00  12.755400       0.07000
639                 Ai  2019-11-17 00:00:00  12.836250       0.07000
638                 Ai  2019-12-23 00:00:00   3.847500       0.03000

In [32]:
# col_list = ['Price_USD', 'Price_Crypto']
# window_list = [7, 14, 30, 60, 90, 180, 365, 730]
# agg_list = ['median', 'max']

# Write for loop to create columns for all new variations
# Delete rows for all but the last row for each Collection_cleaned/Datetime_updated combination
# Create new column that adds 1 day to the Datetime_updated column
# Join new dataframe with dummy dataframe that includes 1 row per day per Collection_cleaned - may not need to do this - problem is that the dates may not align
# Alternative
# Join new dataframe with df_sorted5 on 'Collection_cleaned' and  new date column with df_sorted5['Datetime_daybeforesale']

col_list = ['Price_USD', 'Price_Crypto']
window_list = [7, 14, 30, 60, 90, 180, 365, 730]
agg_list = ['median', 'max']

In [33]:
%%time
# Write for loop to create columns for all new variations

for val in col_list:
    for item in window_list:
        for func in agg_list:
            if func == 'median':
                df_sorted5_priceprep[val+'_'+func+'_'+str(item)+'d'] = df_sorted5_priceprep.groupby(['Collection_cleaned', 'Datetime_updated'])[val].transform(lambda s: s.rolling(item, min_periods=1).median())
            else:
                df_sorted5_priceprep[val+'_'+func+'_'+str(item)+'d'] = df_sorted5_priceprep.groupby(['Collection_cleaned', 'Datetime_updated'])[val].transform(lambda s: s.rolling(item, min_periods=1).max())
    
    # df_collections_otherdata3[str(item)+'d_rolling_avg'] = df_collections_otherdata3.groupby('Collection').rolling(item)['values'].mean().reset_index(drop=True)
    # df_collections_otherdata3[str(item)+'d_rolling_avg'] = df_collections_otherdata3.groupby('Collection')['values'].transform(lambda s: s.rolling(item, min_periods=1).mean())
    #test_df3['Ggl_trends_collection_'+str(item)+'d_rolling_avg'] = test_df3.groupby('Collection')['Ggl_trends_collection'].transform(lambda s: s.rolling(item, min_periods=1).mean())

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

CPU times: user 14min 7s, sys: 21 s, total: 14min 28s
Wall time: 14min 25s

In [34]:
df_sorted5_priceprep.head(25)

,Collection_cleaned,Datetime_updated,Price_USD,Price_Crypto,Price_USD_median_7d,Price_USD_max_7d,Price_USD_median_14d,Price_USD_max_14d,Price_USD_median_30d,Price_USD_max_30d,...,Price_Crypto_median_60d,Price_Crypto_max_60d,Price_Crypto_median_90d,Price_Crypto_max_90d,Price_Crypto_median_180d,Price_Crypto_max_180d,Price_Crypto_median_365d,Price_Crypto_max_365d,Price_Crypto_median_730d,Price_Crypto_max_730d
644,Ai,2019-09-09 00:00:00,0.001805,0.00001,0.001805,0.001805,0.001805,0.001805,0.001805,0.001805,...,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001
641,Ai,2019-09-13 00:00:00,1.631295,0.00900,1.631295,1.631295,1.631295,1.631295,1.631295,1.631295,...,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900
635,Ai,2019-11-03 00:00:00,12.755400,0.07000,12.755400,12.755400,12.755400,12.755400,12.755400,12.755400,...,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000
639,Ai,2019-11-17 00:00:00,12.836250,0.07000,12.836250,12.836250,12.836250,12.836250,12.836250,12.836250,...,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000
638,Ai,2019-12-23 00:00:00,3.847500,0.03000,3.847500,3.847500,3.847500,3.847500,3.847500,3.847500,...,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000
634,Ai,2019-12-23 00:00:00,42.322500,0.33000,23.085000,42.322500,23.085000,42.322500,23.085000,42.322500,...,0.18000,0.33000,0.18000,0.33000,0.18000,0.33000,0.18000,0.33000,0.18000,0.33000
630,Ai,2020-02-22 00:00:00,13.131500,0.05000,13.131500,13.131500,13.131500,13.131500,13.131500,13.131500,...,0.05000,0.05000,0.05000,0.05000,0.05000,0.05000,0.05000,0.05000,0.05000,0.05000
18,Ai,2020-05-15 00:00:00,19.508000,0.10000,19.508000,19.508000,19.508000,19.508000,19.508000,19.508000,...,0.10000,0.10000,0.10000,0.10000,0.10000,0.10000,0.10000,0.10000,0.10000,0.10000
593,Ai,2020-05-30 00:00:00,7.114800,0.03000,7.114800,7.114800,7.114800,7.114800,7.114800,7.114800,...,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000
590,Ai,2020-05-30 00:00:00,7.114800,0.03000,7.114800,7.114800,7.114800,7.114800,7.114800,7.114800,...,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000
7,Ai,2020-06-20 00:00:00,34.479000,0.15000,34.479000,34.479000,34.479000,34.479000,34.479000,34.479000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
1,Ai,2020-06-20 00:00:00,34.479000,0.15000,34.479000,34.479000,34.479000,34.479000,34.479000,34.479000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
19,Ai,2020-06-20 00:00:00,34.479000,0.15000,34.479000,34.479000,34.479000,34.479000,34.479000,34.479000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
4,Ai,2020-06-27 00:00:00,33.378000,0.15000,33.378000,33.378000,33.378000,33.378000,33.378000,33.378000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
5,Ai,2020-06-29 00:00:00,33.983250,0.15000,33.983250,33.983250,33.983250,33.983250,33.983250,33.983250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
2,Ai,2020-06-29 00:00:00,33.983250,0.15000,33.983250,33.983250,33.983250,33.983250,33.983250,33.983250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
643,Ai,2020-07-01 00:00:00,8.260200,0.03600,8.260200,8.260200,8.260200,8.260200,8.260200,8.260200,...,0.03600,0.03600,0.03600,0.03600,0.03600,0.03600,0.03600,0.03600,0.03600,0.03600
9,Ai,2020-07-11 00:00:00,35.838000,0.15000,35.838000,35.838000,35.838000,35.838000,35.838000,35.838000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
13,Ai,2020-07-13 00:00:00,36.007500,0.15000,36.007500,36.007500,36.007500,36.007500,36.007500,36.007500,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
6,Ai,2020-07-20 00:00:00,35.528250,0.15000,35.528250,35.528250,35.528250,35.528250,35.528250,35.528250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
8,Ai,2020-07-20 00:00:00,35.528250,0.15000,35.528250,35.528250,35.528250,35.528250,35.528250,35.528250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
3,Ai,2020-07-20 00:00:00,35.528250,0.15000,35.528250,35.528250,35.528250,35.528250,35.528250,35.528250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
10,Ai,2020-08-17 00:00:00,65.079000,0.15000,65.079000,65.079000,65.079000,65.079000,65.079000,65.079000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000
14,Ai,2020-08-17 00:00:00,86.772000,0.20000,75.925500,86.772000,75.925500,86.772000,75.925500,86.772000,...,0.17500,0.20000,0.17500,0.20000,0.17500,0.20000,0.17500,0.20000,0.17500,0.20000
15,Ai,2020-08-17 00:00:00,86.772000,0.20000,86.772000,86.772000,86.772000,86.772000,86.772000,86.772000,...,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000

In [35]:
%%time
df_sorted5_priceprep["Price_USD_collection_cum_median"] = df_sorted5_priceprep.groupby('Collection_cleaned')['Price_USD'].expanding().median().values
df_sorted5_priceprep["Price_USD_collection_cum_max"] = df_sorted5_priceprep.groupby('Collection_cleaned')['Price_USD'].expanding().max().values
df_sorted5_priceprep["Price_Crypto_collection_cum_median"] = df_sorted5_priceprep.groupby('Collection_cleaned')['Price_Crypto'].expanding().median().values
df_sorted5_priceprep["Price_Crypto_collection_cum_max"] = df_sorted5_priceprep.groupby('Collection_cleaned')['Price_Crypto'].expanding().max().values

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

CPU times: user 32.9 s, sys: 1.38 s, total: 34.3 s
Wall time: 34.3 s

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [36]:
df_sorted5_priceprep.head(5)

,Collection_cleaned,Datetime_updated,Price_USD,Price_Crypto,Price_USD_median_7d,Price_USD_max_7d,Price_USD_median_14d,Price_USD_max_14d,Price_USD_median_30d,Price_USD_max_30d,...,Price_Crypto_median_180d,Price_Crypto_max_180d,Price_Crypto_median_365d,Price_Crypto_max_365d,Price_Crypto_median_730d,Price_Crypto_max_730d,Price_USD_collection_cum_median,Price_USD_collection_cum_max,Price_Crypto_collection_cum_median,Price_Crypto_collection_cum_max
644,Ai,2019-09-09 00:00:00,0.001805,0.00001,0.001805,0.001805,0.001805,0.001805,0.001805,0.001805,...,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,38.7324,38.7324,0.03,0.03
641,Ai,2019-09-13 00:00:00,1.631295,0.00900,1.631295,1.631295,1.631295,1.631295,1.631295,1.631295,...,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900,46.0104,53.2884,0.03,0.03
635,Ai,2019-11-03 00:00:00,12.755400,0.07000,12.755400,12.755400,12.755400,12.755400,12.755400,12.755400,...,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,53.2884,53.2884,0.03,0.03
639,Ai,2019-11-17 00:00:00,12.836250,0.07000,12.836250,12.836250,12.836250,12.836250,12.836250,12.836250,...,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,53.2884,53.2884,0.03,0.03
638,Ai,2019-12-23 00:00:00,3.847500,0.03000,3.847500,3.847500,3.847500,3.847500,3.847500,3.847500,...,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,53.2884,53.2884,0.03,0.03

In [37]:
df_sorted5_priceprep2 = df_sorted5_priceprep.drop_duplicates(subset=['Collection_cleaned', 'Datetime_updated'], keep="last")
print(len(df_sorted5_priceprep2))
df_sorted5_priceprep2.head(25)

83017

,Collection_cleaned,Datetime_updated,Price_USD,Price_Crypto,Price_USD_median_7d,Price_USD_max_7d,Price_USD_median_14d,Price_USD_max_14d,Price_USD_median_30d,Price_USD_max_30d,...,Price_Crypto_median_180d,Price_Crypto_max_180d,Price_Crypto_median_365d,Price_Crypto_max_365d,Price_Crypto_median_730d,Price_Crypto_max_730d,Price_USD_collection_cum_median,Price_USD_collection_cum_max,Price_Crypto_collection_cum_median,Price_Crypto_collection_cum_max
644,Ai,2019-09-09 00:00:00,0.001805,0.00001,0.001805,0.001805,0.001805,0.001805,0.001805,0.001805,...,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,38.732400,38.7324,0.03,0.03
641,Ai,2019-09-13 00:00:00,1.631295,0.00900,1.631295,1.631295,1.631295,1.631295,1.631295,1.631295,...,0.00900,0.00900,0.00900,0.00900,0.00900,0.00900,46.010400,53.2884,0.03,0.03
635,Ai,2019-11-03 00:00:00,12.755400,0.07000,12.755400,12.755400,12.755400,12.755400,12.755400,12.755400,...,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,53.288400,53.2884,0.03,0.03
639,Ai,2019-11-17 00:00:00,12.836250,0.07000,12.836250,12.836250,12.836250,12.836250,12.836250,12.836250,...,0.07000,0.07000,0.07000,0.07000,0.07000,0.07000,53.288400,53.2884,0.03,0.03
634,Ai,2019-12-23 00:00:00,42.322500,0.33000,23.085000,42.322500,23.085000,42.322500,23.085000,42.322500,...,0.18000,0.33000,0.18000,0.33000,0.18000,0.33000,53.288400,88.9092,0.03,0.06
630,Ai,2020-02-22 00:00:00,13.131500,0.05000,13.131500,13.131500,13.131500,13.131500,13.131500,13.131500,...,0.05000,0.05000,0.05000,0.05000,0.05000,0.05000,53.288400,89.7849,0.03,0.06
18,Ai,2020-05-15 00:00:00,19.508000,0.10000,19.508000,19.508000,19.508000,19.508000,19.508000,19.508000,...,0.10000,0.10000,0.10000,0.10000,0.10000,0.10000,53.288400,89.7849,0.03,0.06
590,Ai,2020-05-30 00:00:00,7.114800,0.03000,7.114800,7.114800,7.114800,7.114800,7.114800,7.114800,...,0.03000,0.03000,0.03000,0.03000,0.03000,0.03000,53.288400,89.7849,0.03,0.06
19,Ai,2020-06-20 00:00:00,34.479000,0.15000,34.479000,34.479000,34.479000,34.479000,34.479000,34.479000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,53.288400,89.7849,0.03,0.06
4,Ai,2020-06-27 00:00:00,33.378000,0.15000,33.378000,33.378000,33.378000,33.378000,33.378000,33.378000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,50.532150,89.7849,0.03,0.06
2,Ai,2020-06-29 00:00:00,33.983250,0.15000,33.983250,33.983250,33.983250,33.983250,33.983250,33.983250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,47.775900,89.7849,0.03,0.06
643,Ai,2020-07-01 00:00:00,8.260200,0.03600,8.260200,8.260200,8.260200,8.260200,8.260200,8.260200,...,0.03600,0.03600,0.03600,0.03600,0.03600,0.03600,47.775900,100.9833,0.03,0.06
9,Ai,2020-07-11 00:00:00,35.838000,0.15000,35.838000,35.838000,35.838000,35.838000,35.838000,35.838000,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,47.775900,100.9833,0.03,0.06
13,Ai,2020-07-13 00:00:00,36.007500,0.15000,36.007500,36.007500,36.007500,36.007500,36.007500,36.007500,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,47.775900,100.9833,0.03,0.06
3,Ai,2020-07-20 00:00:00,35.528250,0.15000,35.528250,35.528250,35.528250,35.528250,35.528250,35.528250,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,53.288400,110.0979,0.03,0.06
15,Ai,2020-08-17 00:00:00,86.772000,0.20000,86.772000,86.772000,86.772000,86.772000,86.772000,86.772000,...,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,53.288400,213.9162,0.03,0.12
16,Ai,2020-08-19 00:00:00,82.147000,0.20000,82.147000,82.147000,82.147000,82.147000,82.147000,82.147000,...,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,53.288400,213.9162,0.03,0.12
11,Ai,2020-09-16 00:00:00,55.059750,0.15000,55.059750,55.059750,55.059750,55.059750,55.059750,55.059750,...,0.15000,0.15000,0.15000,0.15000,0.15000,0.15000,53.288400,213.9162,0.03,0.12
12,Ai,2020-09-26 00:00:00,0.035214,0.00010,0.035214,0.035214,0.035214,0.035214,0.035214,0.035214,...,0.00010,0.00010,0.00010,0.00010,0.00010,0.00010,53.383725,213.9162,0.03,0.12
804,Ai,2020-09-29 00:00:00,0.397050,10.00000,0.397050,0.397050,0.397050,0.397050,0.397050,0.397050,...,10.00000,10.00000,10.00000,10.00000,10.00000,10.00000,53.479050,534.7905,0.03,0.30
627,Ai,2020-10-02 00:00:00,189.472250,0.55000,189.472250,189.472250,189.472250,189.472250,189.472250,189.472250,...,0.55000,0.55000,0.55000,0.55000,0.55000,0.55000,53.479050,534.7905,0.03,0.30
820,Ai,2020-10-10 00:00:00,0.844200,20.00000,1.055250,2.110500,1.055250,2.110500,1.055250,2.110500,...,25.00000,50.00000,25.00000,50.00000,25.00000,50.00000,53.479050,534.7905,0.03,0.30
17,Ai,2020-10-20 00:00:00,75.394000,0.20000,75.394000,75.394000,75.394000,75.394000,75.394000,75.394000,...,0.20000,0.20000,0.20000,0.20000,0.20000,0.20000,53.479050,534.7905,0.03,0.30
655,Ai,2020-10-22 00:00:00,0.406295,0.00100,0.406295,0.406295,0.406295,0.406295,0.406295,0.406295,...,0.00100,0.00100,0.00100,0.00100,0.00100,0.00100,53.479050,534.7905,0.03,0.30
809,Ai,2020-10-25 00:00:00,0.561975,15.00000,0.561975,0.561975,0.561975,0.561975,0.561975,0.561975,...,15.00000,15.00000,15.00000,15.00000,15.00000,15.00000,53.479050,534.7905,0.03,0.30

In [38]:
df_sorted5_priceprep2['Date_new'] = pd.to_datetime(df_sorted5_priceprep2['Datetime_updated'])
# print(type(df_sorted5_priceprep2['Datetime_updated']))
# type(df_sorted5_priceprep2['Datetime_updated'][0])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [39]:
df_sorted5_priceprep2.head(5)

,Collection_cleaned,Datetime_updated,Price_USD,Price_Crypto,Price_USD_median_7d,Price_USD_max_7d,Price_USD_median_14d,Price_USD_max_14d,Price_USD_median_30d,Price_USD_max_30d,...,Price_Crypto_max_180d,Price_Crypto_median_365d,Price_Crypto_max_365d,Price_Crypto_median_730d,Price_Crypto_max_730d,Price_USD_collection_cum_median,Price_USD_collection_cum_max,Price_Crypto_collection_cum_median,Price_Crypto_collection_cum_max,Date_new
644,Ai,2019-09-09 00:00:00,0.001805,0.00001,0.001805,0.001805,0.001805,0.001805,0.001805,0.001805,...,0.00001,0.00001,0.00001,0.00001,0.00001,38.7324,38.7324,0.03,0.03,2019-09-09
641,Ai,2019-09-13 00:00:00,1.631295,0.00900,1.631295,1.631295,1.631295,1.631295,1.631295,1.631295,...,0.00900,0.00900,0.00900,0.00900,0.00900,46.0104,53.2884,0.03,0.03,2019-09-13
635,Ai,2019-11-03 00:00:00,12.755400,0.07000,12.755400,12.755400,12.755400,12.755400,12.755400,12.755400,...,0.07000,0.07000,0.07000,0.07000,0.07000,53.2884,53.2884,0.03,0.03,2019-11-03
639,Ai,2019-11-17 00:00:00,12.836250,0.07000,12.836250,12.836250,12.836250,12.836250,12.836250,12.836250,...,0.07000,0.07000,0.07000,0.07000,0.07000,53.2884,53.2884,0.03,0.03,2019-11-17
634,Ai,2019-12-23 00:00:00,42.322500,0.33000,23.085000,42.322500,23.085000,42.322500,23.085000,42.322500,...,0.33000,0.18000,0.33000,0.18000,0.33000,53.2884,88.9092,0.03,0.06,2019-12-23

In [63]:
df_collections_prep = pd.DataFrame({'Date': pd.date_range(start='7/1/2017', end='4/27/2021', freq='D'), 'Blank': np.nan})
df_collections_prep.head(5)

        Date  Blank
0 2017-07-01    NaN
1 2017-07-02    NaN
2 2017-07-03    NaN
3 2017-07-04    NaN
4 2017-07-05    NaN

In [69]:
df_collection_cleaned_unique = pd.DataFrame(df_sorted5['Collection_cleaned'].unique())
df_collection_cleaned_unique.columns = ['Collection_cleaned']
df_collection_cleaned_unique.head()

  Collection_cleaned
0                 Ai
1        Alottamoney
2   Apeinfinanceshop
3            Apeonly
4     Appresidential

In [70]:
df_collections_prep['key'] = 0
df_collection_cleaned_unique['key'] = 0
df_collections_prep = pd.merge(df_collections_prep, df_collection_cleaned_unique, on='key').drop('key', axis=1)
print(len(df_collections_prep))
df_collections_prep.head()

6459728

        Date  Blank Collection_cleaned
0 2017-07-01    NaN                 Ai
1 2017-07-01    NaN        Alottamoney
2 2017-07-01    NaN   Apeinfinanceshop
3 2017-07-01    NaN            Apeonly
4 2017-07-01    NaN     Appresidential

In [71]:
type(df_collections_prep['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [72]:
print(len(df_collections_prep))
df_collections_prep.head(5)

6459728

        Date  Blank Collection_cleaned
0 2017-07-01    NaN                 Ai
1 2017-07-01    NaN        Alottamoney
2 2017-07-01    NaN   Apeinfinanceshop
3 2017-07-01    NaN            Apeonly
4 2017-07-01    NaN     Appresidential

In [73]:
df_collections_prep = pd.concat([df_collections_prep, df_collection_cleaned_unique], ignore_index=True, axis=0)
print(len(df_collections_prep))
df_collections_prep.head()

6464352

        Date  Blank Collection_cleaned  key
0 2017-07-01    NaN                 Ai  NaN
1 2017-07-01    NaN        Alottamoney  NaN
2 2017-07-01    NaN   Apeinfinanceshop  NaN
3 2017-07-01    NaN            Apeonly  NaN
4 2017-07-01    NaN     Appresidential  NaN

In [74]:
df_collections_prep.tail(5)

        Date  Blank Collection_cleaned  key
6464347  NaT    NaN              Terra  0.0
6464348  NaT    NaN            Unisock  0.0
6464349  NaT    NaN        Unstoppable  0.0
6464350  NaT    NaN            Urbitid  0.0
6464351  NaT    NaN         Yinsurenft  0.0

In [75]:
len(df_collections_prep)

6464352

In [76]:
type(df_collections_prep['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [77]:
df_sorted5.columns
print(type(df_sorted5['Datetime_updated'][0]))
type(df_sorted5['Datetime_daybeforesale'][0])

<class 'str'>

pandas._libs.tslibs.timestamps.Timestamp

In [78]:
df_sorted5['Datetime_dayaftersale'] = df_sorted5['Datetime_updated_dt'] + pd.Timedelta(days=1)
df_sorted5.head(5)

,Smart_contract,ID_token,Transaction_hash,Seller_address,Seller_username,Buyer_address,Buyer_username,Image_url_1,Image_url_2,Image_url_3,...,WAX_price_30d_rolling_avg,WAX_price_60d_rolling_avg,WAX_price_90d_rolling_avg,Ggl_trends_collection,Ggl_trends_collection_7d_rolling_avg,Ggl_trends_collection_14d_rolling_avg,Ggl_trends_collection_30d_rolling_avg,Ggl_trends_collection_60d_rolling_avg,Ggl_trends_collection_90d_rolling_avg,Datetime_dayaftersale
644,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,59,0xf31852b040f32d14322e1b599cac38eadedb1e145cfc...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0xfdc34f61ccc6e5cbf8d168614ab29bae624085c9,KM-ATT,https://lh3.googleusercontent.com/SLoh29AeY88B...,http://www.aicryptoart.org/artpieces/59__Great...,https://lh3.googleusercontent.com/SLoh29AeY88B...,...,0.049710,0.053525,0.065018,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-10
641,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,39,0x59c45346fed5b753e0ce1d51dd9d56e1df5a27dd620d...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x73aab1333dc134e34f5c7b492f90e76cd7589476,rabanheidr,https://lh3.googleusercontent.com/JqKxBV1odtH7...,http://www.aicryptoart.org/artpieces/39__Mr._P...,https://lh3.googleusercontent.com/JqKxBV1odtH7...,...,0.046837,0.052652,0.062263,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-14
635,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,23,0xcd79d4cd1d12c00fcc06a2f3f9eef408fe03dccadecd...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x187d6e8741af35c45198ebec83905eb23e742b15,ciobo,https://lh3.googleusercontent.com/31JMA6rmMom6...,http://www.aicryptoart.org/artpieces/23_dont_f...,https://lh3.googleusercontent.com/31JMA6rmMom6...,...,0.029983,0.034100,0.040282,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-04
639,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,28,0x9efbadc255a3b7b68b78b1f497787a3d2366c3799359...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0x1eef91b7db2848a528a0762b0c5327a53b2eadbe,Lifenow,https://lh3.googleusercontent.com/ZRDrLtIrl0qv...,http://www.aicryptoart.org/artpieces/28__Mrs._...,https://lh3.googleusercontent.com/ZRDrLtIrl0qv...,...,0.030293,0.031777,0.036091,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-18
638,0x8ae8d2ae74a96595bcdab803b563f594009e3db2,26,0x82fc5f80b55584526ebbfad26329f9e24e4626338376...,0xd5f4bbd4d1f9ecf3bccb12ac8a2c8bdc5b45b482,Crypto_Wizard_89,0xcd4fec10c8ad4873e209062b31defb684ff8cb7c,cryptotonya,https://lh3.googleusercontent.com/MfxXntL-jf1-...,http://www.aicryptoart.org/artpieces/26__Prof....,https://lh3.googleusercontent.com/MfxXntL-jf1-...,...,0.023727,0.026798,0.028288,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-24

In [79]:
df_collections_prep2 = df_collections_prep.merge(df_sorted5_priceprep2, left_on=['Collection_cleaned', 'Date'], right_on=['Collection_cleaned', 'Date_new'], how='left')
# df_collections_otherdata2.fillna(method='ffill', inplace=True)
df_collections_prep2.head(5)

,Date,Blank,Collection_cleaned,key,Datetime_updated,Price_USD,Price_Crypto,Price_USD_median_7d,Price_USD_max_7d,Price_USD_median_14d,...,Price_Crypto_max_180d,Price_Crypto_median_365d,Price_Crypto_max_365d,Price_Crypto_median_730d,Price_Crypto_max_730d,Price_USD_collection_cum_median,Price_USD_collection_cum_max,Price_Crypto_collection_cum_median,Price_Crypto_collection_cum_max,Date_new
0,2017-07-01,NaN,Ai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,2017-07-01,NaN,Alottamoney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,2017-07-01,NaN,Apeinfinanceshop,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,2017-07-01,NaN,Apeonly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,2017-07-01,NaN,Appresidential,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [80]:
df_collections_prep2.tail(10)

,Date,Blank,Collection_cleaned,key,Datetime_updated,Price_USD,Price_Crypto,Price_USD_median_7d,Price_USD_max_7d,Price_USD_median_14d,...,Price_Crypto_max_180d,Price_Crypto_median_365d,Price_Crypto_max_365d,Price_Crypto_median_730d,Price_Crypto_max_730d,Price_USD_collection_cum_median,Price_USD_collection_cum_max,Price_Crypto_collection_cum_median,Price_Crypto_collection_cum_max,Date_new
6464342,NaT,NaN,Zyzzyvasalgorithmicart,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464343,NaT,NaN,Zzsun,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464344,NaT,NaN,Ethercardsfonder,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464345,NaT,NaN,Methodnft,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464346,NaT,NaN,Pgfk,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464347,NaT,NaN,Terra,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464348,NaT,NaN,Unisock,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464349,NaT,NaN,Unstoppable,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464350,NaT,NaN,Urbitid,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
6464351,NaT,NaN,Yinsurenft,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [81]:
type(df_collections_prep2['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [82]:
df_collections_prep2.columns

Index(['Date', 'Blank', 'Collection_cleaned', 'key', 'Datetime_updated',
       'Price_USD', 'Price_Crypto', 'Price_USD_median_7d', 'Price_USD_max_7d',
       'Price_USD_median_14d', 'Price_USD_max_14d', 'Price_USD_median_30d',
       'Price_USD_max_30d', 'Price_USD_median_60d', 'Price_USD_max_60d',
       'Price_USD_median_90d', 'Price_USD_max_90d', 'Price_USD_median_180d',
       'Price_USD_max_180d', 'Price_USD_median_365d', 'Price_USD_max_365d',
       'Price_USD_median_730d', 'Price_USD_max_730d', 'Price_Crypto_median_7d',
       'Price_Crypto_max_7d', 'Price_Crypto_median_14d',
       'Price_Crypto_max_14d', 'Price_Crypto_median_30d',
       'Price_Crypto_max_30d', 'Price_Crypto_median_60d',
       'Price_Crypto_max_60d', 'Price_Crypto_median_90d',
       'Price_Crypto_max_90d', 'Price_Crypto_median_180d',
       'Price_Crypto_max_180d', 'Price_Crypto_median_365d',
       'Price_Crypto_max_365d', 'Price_Crypto_median_730d',
       'Price_Crypto_max_730d', 'Price_USD_collection_cum_median',
       'Price_USD_collection_cum_max', 'Price_Crypto_collection_cum_median',
       'Price_Crypto_collection_cum_max', 'Date_new'],
      dtype='object')

In [83]:
df_collections_prep2.update(df_collections_prep2.groupby(['Collection_cleaned','Date'])['Price_USD_median_7d', 'Price_USD_max_7d', 'Price_USD_median_14d', 'Price_USD_max_14d',
                                                                                       'Price_USD_median_30d', 'Price_USD_max_30d', 'Price_USD_median_60d', 'Price_USD_max_60d', 
                                                                                       'Price_USD_median_90d', 'Price_USD_max_90d', 'Price_USD_median_180d', 'Price_USD_max_180d',
                                                                                       'Price_USD_median_365d', 'Price_USD_max_365d', 'Price_USD_median_730d',
                                                                                       'Price_USD_max_730d', 'Price_Crypto_median_7d', 'Price_Crypto_max_7d', 
                                                                                       'Price_Crypto_median_14d', 'Price_Crypto_max_14d', 'Price_Crypto_median_30d',
                                                                                       'Price_Crypto_max_30d', 'Price_Crypto_median_60d', 'Price_Crypto_max_60d',
                                                                                       'Price_Crypto_median_90d', 'Price_Crypto_max_90d', 'Price_Crypto_median_180d',
                                                                                       'Price_Crypto_max_180d', 'Price_Crypto_median_365d', 'Price_Crypto_max_365d',
                                                                                       'Price_Crypto_median_730d', 'Price_Crypto_max_730d', 'Price_USD_collection_cum_median',
                                                                                       'Price_USD_collection_cum_max', 'Price_Crypto_collection_cum_median',
                                                                                       'Price_Crypto_collection_cum_max'].ffill().fillna(0))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

In [84]:
df_collections_prep2.isna().sum()

Date                                     4624
Blank                                 6464352
Collection_cleaned                          0
key                                   6459728
Datetime_updated                      6381335
Price_USD                             6382719
Price_Crypto                          6381335
Price_USD_median_7d                         0
Price_USD_max_7d                            0
Price_USD_median_14d                        0
Price_USD_max_14d                           0
Price_USD_median_30d                        0
Price_USD_max_30d                           0
Price_USD_median_60d                        0
Price_USD_max_60d                           0
Price_USD_median_90d                        0
Price_USD_max_90d                           0
Price_USD_median_180d                       0
Price_USD_max_180d                          0
Price_USD_median_365d                       0
Price_USD_max_365d                          0
Price_USD_median_730d                       0
Price_USD_max_730d                          0
Price_Crypto_median_7d                      0
Price_Crypto_max_7d                         0
Price_Crypto_median_14d                     0
Price_Crypto_max_14d                        0
Price_Crypto_median_30d                     0
Price_Crypto_max_30d                        0
Price_Crypto_median_60d                     0
Price_Crypto_max_60d                        0
Price_Crypto_median_90d                     0
Price_Crypto_max_90d                        0
Price_Crypto_median_180d                    0
Price_Crypto_max_180d                       0
Price_Crypto_median_365d                    0
Price_Crypto_max_365d                       0
Price_Crypto_median_730d                    0
Price_Crypto_max_730d                       0
Price_USD_collection_cum_median             0
Price_USD_collection_cum_max                0
Price_Crypto_collection_cum_median          0
Price_Crypto_collection_cum_max             0
Date_new                              6381335
dtype: int64

In [52]:
df_sorted5.columns

Index(['Smart_contract', 'ID_token', 'Transaction_hash', 'Seller_address',
       'Seller_username', 'Buyer_address', 'Buyer_username', 'Image_url_1',
       'Image_url_2', 'Image_url_3', 'Image_url_4', 'Price_Crypto', 'Crypto',
       'Price_USD', 'Name', 'Description', 'Collection', 'Market',
       'Datetime_updated', 'Datetime_updated_seconds', 'Permanent_link',
       'Unique_id_collection', 'Collection_cleaned', 'Category',
       'Datetime_updated_dt', 'Datetime_daybeforesale', 'nft_sales_count',
       'First_item_Collection_cleaned', 'First_item_Unique_id_collection',
       'Previous_Price_USD', 'Previous_Datetime_updated_seconds',
       'Elapsed_time', 'Price_increase', 'Price_diff', 'Price_diff_pctg',
       'GoogleTrends', 'BTC_price', 'ETH_price', 'MANA_price', 'WAX_price',
       'GoogleTrends_7d_rolling_avg', 'GoogleTrends_14d_rolling_avg',
       'GoogleTrends_30d_rolling_avg', 'GoogleTrends_60d_rolling_avg',
       'GoogleTrends_90d_rolling_avg', 'BTC_price_7d_rolling_avg',
       'BTC_price_14d_rolling_avg', 'BTC_price_30d_rolling_avg',
       'BTC_price_60d_rolling_avg', 'BTC_price_90d_rolling_avg',
       'ETH_price_7d_rolling_avg', 'ETH_price_14d_rolling_avg',
       'ETH_price_30d_rolling_avg', 'ETH_price_60d_rolling_avg',
       'ETH_price_90d_rolling_avg', 'MANA_price_7d_rolling_avg',
       'MANA_price_14d_rolling_avg', 'MANA_price_30d_rolling_avg',
       'MANA_price_60d_rolling_avg', 'MANA_price_90d_rolling_avg',
       'WAX_price_7d_rolling_avg', 'WAX_price_14d_rolling_avg',
       'WAX_price_30d_rolling_avg', 'WAX_price_60d_rolling_avg',
       'WAX_price_90d_rolling_avg', 'Ggl_trends_collection',
       'Ggl_trends_collection_7d_rolling_avg',
       'Ggl_trends_collection_14d_rolling_avg',
       'Ggl_trends_collection_30d_rolling_avg',
       'Ggl_trends_collection_60d_rolling_avg',
       'Ggl_trends_collection_90d_rolling_avg', 'Datetime_dayaftersale'],
      dtype='object')

In [85]:
df_collections_prep2.columns

Index(['Date', 'Blank', 'Collection_cleaned', 'key', 'Datetime_updated',
       'Price_USD', 'Price_Crypto', 'Price_USD_median_7d', 'Price_USD_max_7d',
       'Price_USD_median_14d', 'Price_USD_max_14d', 'Price_USD_median_30d',
       'Price_USD_max_30d', 'Price_USD_median_60d', 'Price_USD_max_60d',
       'Price_USD_median_90d', 'Price_USD_max_90d', 'Price_USD_median_180d',
       'Price_USD_max_180d', 'Price_USD_median_365d', 'Price_USD_max_365d',
       'Price_USD_median_730d', 'Price_USD_max_730d', 'Price_Crypto_median_7d',
       'Price_Crypto_max_7d', 'Price_Crypto_median_14d',
       'Price_Crypto_max_14d', 'Price_Crypto_median_30d',
       'Price_Crypto_max_30d', 'Price_Crypto_median_60d',
       'Price_Crypto_max_60d', 'Price_Crypto_median_90d',
       'Price_Crypto_max_90d', 'Price_Crypto_median_180d',
       'Price_Crypto_max_180d', 'Price_Crypto_median_365d',
       'Price_Crypto_max_365d', 'Price_Crypto_median_730d',
       'Price_Crypto_max_730d', 'Price_USD_collection_cum_median',
       'Price_USD_collection_cum_max', 'Price_Crypto_collection_cum_median',
       'Price_Crypto_collection_cum_max', 'Date_new'],
      dtype='object')

In [86]:
df_sorted6 = df_sorted5.merge(df_collections_prep2, left_on=['Collection_cleaned', 'Datetime_daybeforesale'], right_on=['Collection_cleaned', 'Date_new'], how='left')
# df_collections_otherdata2.fillna(method='ffill', inplace=True)
print(len(df_sorted6))
df_sorted6.head(5)

MemoryError: Unable to allocate 1.72 GiB for an array with shape (38, 6071027) and data type float64

In [ ]:
df_sorted6.isna().sum()

In [ ]:
df_sorted7 = df_sorted6.drop(columns=['Date','Blank','Datetime_updated_y','Price_USD_y','Price_Crypto_y','Date_new']).rename(columns={'Price_Crypto_x':'Price_Crypto', 'Price_USD_x':'Price_USD', 'Datetime_updated_x':'Datetime_updated'})
len(df_sorted7)

In [ ]:
for col in df_sorted7.columns:
    print(col)

In [58]:
# df_sorted7.to_pickle('df_additional_values.pkl')

In [162]:
# from google.colab import drive
# drive.mount('/content/drive')

In [154]:
# for col in df_sorted6.columns:
#     print(col)

In [59]:
# df_sorted6.loc[df_sorted6['First_item_Collection_cleaned'] == 1]

In [61]:
# print(len(df_collections_prep))

In [62]:
# df_sorted5.to_pickle('df_additional_values.pkl')

In [59]:
df_median_prep = df_sorted5[['Price_Crypto', 'Price_USD', 'Datetime_updated', 'Datetime_updated_seconds', 'Unique_id_collection', 
                                   'Collection_cleaned', 'Category', 'Datetime_updated_dt', 'Datetime_daybeforesale', 'First_item_Collection_cleaned']]
df_median_prep.head(5)

,Price_Crypto,Price_USD,Datetime_updated,Datetime_updated_seconds,Unique_id_collection,Collection_cleaned,Category,Datetime_updated_dt,Datetime_daybeforesale,First_item_Collection_cleaned
644,0.00001,0.001805,2019-09-09 00:00:00,2019-09-09 20:00:35,"('Aicryptoart', '59')",Ai,Art,2019-09-09,2019-09-08,1
641,0.00900,1.631295,2019-09-13 00:00:00,2019-09-13 22:35:55,"('Aicryptoart', '39')",Ai,Art,2019-09-13,2019-09-12,0
635,0.07000,12.755400,2019-11-03 00:00:00,2019-11-03 08:20:12,"('Aicryptoart', '23')",Ai,Art,2019-11-03,2019-11-02,0
639,0.07000,12.836250,2019-11-17 00:00:00,2019-11-17 18:55:04,"('Aicryptoart', '28')",Ai,Art,2019-11-17,2019-11-16,0
638,0.03000,3.847500,2019-12-23 00:00:00,2019-12-23 03:15:21,"('Aicryptoart', '26')",Ai,Art,2019-12-23,2019-12-22,0

In [62]:
df_collections_median = df_median_prep.pivot(index=['Datetime_updated_dt', 'Datetime_daybeforesale'], columns='Collection_cleaned')
print(len(df_collections_median))
df_collections_median.head(5)

ValueError: Index contains duplicate entries, cannot reshape

In [196]:
start_date = test_df.index.min() - pd.DateOffset(day=1)
end_date = test_df.index.max() + pd.DateOffset(day=27)
print(start_date)
print(end_date)

2017-07-01 00:00:00
2021-04-27 00:00:00

In [201]:
dates = pd.date_range(start_date, end_date, freq='D')
dates.name = 'date'
test_df = test_df.reindex(dates, method='ffill')
print(len(test_df))
test_df.head(25)

1397

           values                                                       ...  \
Collection     13 1997 Aella Alchemy  Ali Anon Ants  Arc Artemis   Atm  ...
date                                                                    ...
2017-07-01    NaN  NaN   NaN     NaN  NaN  NaN  NaN  NaN     NaN   NaN  ...
2017-07-02    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-03    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-04    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-05    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-06    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-07    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-08    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-09    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-10    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-11    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-12    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-13    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-14    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-15    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-16    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-17    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-18    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-19    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-20    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-21    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-22    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0  19.0  ...
2017-07-23    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-24    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...
2017-07-25    0.0  0.0   0.0     0.0  0.0  0.0  0.0  0.0     0.0   0.0  ...

                                                                         \
Collection deadmau5 dust games hodlgod inteligencia pepe rplanet weezer
date
2017-07-01      NaN  NaN   NaN     NaN          NaN  NaN     NaN    NaN
2017-07-02      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-03      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-04      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-05      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-06      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-07      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-08      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-09      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-10      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-11      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-12      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-13      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-14      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-15      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-16      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-17      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-18      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-19      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-20      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-21      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-22      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-23      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-24      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0
2017-07-25      0.0  0.0   0.0     0.0          0.0  0.0     0.0    0.0


Collection writer   xp
date
2017-07-01    NaN  NaN
2017-07-02    0.0  0.0
2017-07-03    0.0  0.0
2017-07-04    0.0  0.0
2017-07-05    0.0  0.0
2017-07-06    0.0  0.0
2017-07-07    0.0  0.0
2017-07-08    0.0  0.0
2017-07-09    0.0  0.0
2017-07-10    0.0  0.0
2017-07-11    0.0  0.0
2017-07-12    0.0  0.0
2017-07-13    0.0  0.0
2017-07-14    0.0  0.0
2017-07-15    0.0  0.0
2017-07-16    0.0  0.0
2017-07-17    0.0  0.0
2017-07-18    0.0  0.0
2017-07-19    0.0  0.0
2017-07-20    0.0  0.0
2017-07-21    0.0  0.0
2017-07-22    0.0  0.0
2017-07-23    0.0  0.0
2017-07-24    0.0  0.0
2017-07-25    0.0  0.0

[25 rows x 200 columns]

In [208]:
test_df2 = test_df.stack().reset_index()
test_df2.head()

        date Collection  values
0 2017-07-02         13     0.0
1 2017-07-02       1997     0.0
2 2017-07-02      Aella     0.0
3 2017-07-02    Alchemy     0.0
4 2017-07-02        Ali     0.0

In [209]:
# test_df2 = test_df.reset_index()
print(len(test_df2))
# test_df2.head(5)

279200

In [218]:
test_df3 = test_df2.sort_values(['Collection', 'date'])
test_df3.head()

          date Collection  values
0   2017-07-02         13     0.0
200 2017-07-03         13     0.0
400 2017-07-04         13     0.0
600 2017-07-05         13     0.0
800 2017-07-06         13     0.0

In [219]:
# test_df3 = test_df2.reset_index().stack()
# test_df3.head(5)

In [220]:
test_df3.tail(10)

             date Collection  values
277399 2021-04-18         xp     0.0
277599 2021-04-19         xp     0.0
277799 2021-04-20         xp     0.0
277999 2021-04-21         xp     0.0
278199 2021-04-22         xp     0.0
278399 2021-04-23         xp     0.0
278599 2021-04-24         xp     0.0
278799 2021-04-25         xp     0.0
278999 2021-04-26         xp     0.0
279199 2021-04-27         xp     0.0

In [221]:
test_df3.loc[test_df3['Collection'] == 'weezer']

             date Collection  values
197    2017-07-02     weezer     0.0
397    2017-07-03     weezer     0.0
597    2017-07-04     weezer     0.0
797    2017-07-05     weezer     0.0
997    2017-07-06     weezer     0.0
...           ...        ...     ...
278397 2021-04-23     weezer     7.0
278597 2021-04-24     weezer     7.0
278797 2021-04-25     weezer   100.0
278997 2021-04-26     weezer   100.0
279197 2021-04-27     weezer   100.0

[1396 rows x 3 columns]

In [222]:
# test_df3.to_pickle('df_googletrends_collections_daily.pkl')

In [223]:
test_df3.rename({'values': 'Ggl_trends_collection'}, axis=1, inplace=True)
test_df3.head()

          date Collection  Ggl_trends_collection
0   2017-07-02         13                    0.0
200 2017-07-03         13                    0.0
400 2017-07-04         13                    0.0
600 2017-07-05         13                    0.0
800 2017-07-06         13                    0.0

In [224]:
window_list = [7, 14, 30, 60, 90]

for item in window_list:
    # df_collections_otherdata3[str(item)+'d_rolling_avg'] = df_collections_otherdata3.groupby('Collection').rolling(item)['values'].mean().reset_index(drop=True)
    # df_collections_otherdata3[str(item)+'d_rolling_avg'] = df_collections_otherdata3.groupby('Collection')['values'].transform(lambda s: s.rolling(item, min_periods=1).mean())
    test_df3['Ggl_trends_collection_'+str(item)+'d_rolling_avg'] = test_df3.groupby('Collection')['Ggl_trends_collection'].transform(lambda s: s.rolling(item, min_periods=1).mean())
    
test_df3.head(5)

,date,Collection,Ggl_trends_collection,Ggl_trends_collection_7d_rolling_avg,Ggl_trends_collection_14d_rolling_avg,Ggl_trends_collection_30d_rolling_avg,Ggl_trends_collection_60d_rolling_avg,Ggl_trends_collection_90d_rolling_avg
0,2017-07-02,13,0.0,0.0,0.0,0.0,0.0,0.0
200,2017-07-03,13,0.0,0.0,0.0,0.0,0.0,0.0
400,2017-07-04,13,0.0,0.0,0.0,0.0,0.0,0.0
600,2017-07-05,13,0.0,0.0,0.0,0.0,0.0,0.0
800,2017-07-06,13,0.0,0.0,0.0,0.0,0.0,0.0